# -*- coding: utf-8 -*-
"""IOT Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v_GD5bV3bLvoGh-lDMcMSsYDb_XLmVpM
"""

pip install git+https://github.com/ultralytics/ultralytics.git@main

# Importing the required libraries
from ultralytics import YOLO
import matplotlib.pyplot as plt
import cv2
import os
import random
import pandas as pd
import matplotlib.image as mpimg

# Commented out IPython magic to ensure Python compatibility.
# Enabling inline plotting for Matplotlib in Jupyter Notebook
# %matplotlib inline

# Setting plot style
plt.style.use('ggplot')

from google.colab import drive
drive.mount('/content/drive')

project_dir = '/content/drive/MyDrive/IOT Project'

# Loading a pretrained model
model = YOLO(project_dir + '/Yolov8/yolov8x.pt')

# Training the model
model.train(data = project_dir + '/Yolov8/dataset/data.yaml',
            epochs = 20,
            imgsz = 460,
            seed = 42)

